### ISSUE TITLE
Plunker with angular 2.0.0 not working

### ISSUE THREAD

**Issue by LeResKP** [shlomiassaf/angular2-modal#218]
Hello,

I fork your plnkr and updated to angular 2.0.0 with @2.0.0-beta.13 but there is an error:

zone.js@0.6.12?main=browser:463 Error: Uncaught (in promise): TypeError: Zone.assertZonePatched is not a function(…)

Here is the plnkr: http://plnkr.co/edit/zWkmrab0HcgoWfxmwzob?p=preview

Do you have a plnkr working with angular 2.0.0 ? I think I have an issue with angular2-modal but I need to create a plnkr to reproduce it (it seems the same issue than here: https://github.com/shlomiassaf/angular2-modal/issues/217).

Also I clone your repo to try the last version with the issue https://github.com/shlomiassaf/angular2-modal/issues/213 fixed but I didn't manage to install it correcly. Can you explain me how to install the dev version ?

Thanks,
Aurélien

**Comment by animator013** [comment]
As of angular 2.0.0-rc.7, zone.js@0.6.21 is required.

**Comment by shlomiassaf** [comment]
@LeResKP Try version 2.0.1 it has the `node` fix.

To install the dev it's just npm install and npm run start.

**Comment by shlomiassaf** [comment]
Updated plunker to work with latest.

**Comment by LeResKP** [comment]
@animator013 : thks for the info

@shlomiassaf : thks for the new release I will give a try. Where is the plunker with latest ?
When I try to install the dev version, it was on my project. I tried npm install pathtorepo/angular2-modal but import didn't work. Perhaps it's not the good way ?

**Comment by h284611** [comment]
I also want to know where to find the plunker with the latest. This one http://embed.plnkr.co/mbPzd8/ is using RC5 and I am getting errors after moving the example into the Angular 2.0.1 environment. 

It would be really helpful if you can let us know. Thanks.
