### ISSUE TITLE
error TS2688: Cannot find type definition file for 'node'.

### ISSUE THREAD

**Issue by dirtyvader** [shlomiassaf/angular2-modal#213]
* Updated my project to angular 2.0.1
* Updated typings to latest: npm run typings -- install dt~node --save --global
* Updated angular2-modal to 2.0.0 (When I start the project, it was 2.0.0-beta13)

**Comment by shlomiassaf** [comment]
@dirtyvader angular2-modal doesn't require you to install typings.
I use `@types`

**Comment by cksdnjs4113** [comment]
This error also appears in my project after reinstalling angula2-modal.
It was working fine before.. 

node_modules/angular2-modal/esm/models/errors.d.ts(1,1): error TS2688: Cannot find type definition file for 'node'.
node_modules/angular2-modal/esm/providers/modal.d.ts(1,1): error TS2688: Cannot find type definition file for 'node'.

**Comment by lyorix** [comment]
I was using the angular2-modal@2.0.0-beta13 with angular@2.0.0 without any issue (except #207). 
I updated my project with angula@2.0.1 & angular2-modal@2.0.0-beta14 for AoT compilation support.
I have now the same issue dirtyvader mentioned:
node_modules/angular2-modal/esm/models/errors.d.ts(1,1): error TS2688: Cannot find type definition file for 'node'.
node_modules/angular2-modal/esm/providers/modal.d.ts(1,1): error TS2688: Cannot find type definition file for 'node'.

Any idea?
Thx

**Comment by cksdnjs4113** [comment]
Just adding more info above, I have replaced previous installed angular2-modal in the node_module. It works fine, however, as soon as I reinstall the angular2-modal, the error above appears again. I'm using 2.0.0-beta13

**Comment by shlomiassaf** [comment]
Can you each write the import method you use?webpack? SystemJS? Etc...

**Comment by cksdnjs4113** [comment]
I use systemjs

**Comment by lukaskopenec** [comment]
I am using webpack, but I am having the same issue. No problem with the same configuration in beta 13.

**Comment by dirtyvader** [comment]
SystemJS too. Settings not changed since it worked (angular 2.0.0 & angular2-modal beta 13)

**Comment by tlorenzetti** [comment]
Same here with Webpack. The same configuration worked with angular-2.0.0 and angular2-modal beta.13.

**Comment by lyorix** [comment]
The error appears during transpilation process (running tsc):  "compilerOptions": {"target": "es5","module": "commonjs","moduleResolution": "node"

**Comment by CaselIT** [comment]
@shlomiassaf 
The first line on both `esm/models/errors.d.ts` and `esm/providers/modal.d.ts` is `/// <reference types="node" />`.
Removing it removes the compilation problem.

**Comment by kisdaniel** [comment]
I have a same bug with` "angular2-modal": "^2.0.0-beta.13",`:

> 
> node_modules/angular2-modal/esm/models/errors.d.ts(1,1): error TS2688: Cannot find type definition file for 'node'.
> node_modules/angular2-modal/esm/providers/modal.d.ts(1,1): error TS2688: Cannot find type definition file for 'node'.
> 
>

**Comment by kisdaniel** [comment]
my package.json:

```
{
  "name": "admin-ui",
  "version": "1.0.0",
  "scripts": {
    "start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" ",
    "lite": "lite-server",
    "postinstall": "typings install",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "typings": "typings"
  },
  "license": "ISC",
  "dependencies": {
    "@angular/common": "~2.0.1",
    "@angular/compiler": "~2.0.1",
    "@angular/compiler-cli": "0.6.3",
    "@angular/core": "~2.0.1",
    "@angular/forms": "~2.0.1",
    "@angular/http": "~2.0.1",
    "@angular/platform-browser": "~2.0.1",
    "@angular/platform-browser-dynamic": "~2.0.1",
    "@angular/router": "~3.0.1",
    "@angular/upgrade": "~2.0.1",
    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.39",
    "zone.js": "^0.6.25",
    "angular2-in-memory-web-api": "0.0.21",

    "angular2-modal": "^2.0.0-beta.12",
    "bootstrap": "^3.3.7",
    "font-awesome": "^4.6.3",
    "jquery": "^3.1.1",
    "momentjs": "^1.1.17",
    "ng2-translate": "^2.5.0"
  },
  "devDependencies": {
    "concurrently": "^3.0.0",
    "tslint": "^3.15.1",
    "lite-server": "^2.2.0",
    "typescript": "^2.0.3",
    "typings": "^1.4.0"
  }
}

```

**Comment by halfonf** [comment]
To me, you all have to migrate to typescript 2.0 remove the typings and import the @typing libs in your package.json.

I had this issue and it solved it.

**Comment by dirtyvader** [comment]
@halonf Can you explain more about that ? I'm new to typescript and typings

**Comment by CaselIT** [comment]
@halfonf you should not have to use the `node` typings in the front-end since you are not running on node but in the browser.

**Comment by CaselIT** [comment]
@kisdaniel you have `"angular2-modal": "^2.0.0-beta.12"` so npm probably installed the v.2.0.0. Change it to `"angular2-modal": "2.0.0-beta.13"` and the problem should not be there anymore. Of course then you cannot use angular 2.0.1...

**Comment by shlomiassaf** [comment]
Hi guys
I'll issue a fix later today 
Thanks

**Comment by cksdnjs4113** [comment]
I am still getting the error.. Is it just me? (I am using beta-13)

**Comment by kisdaniel** [comment]
can anyone explain which version is compatible with angular 2.0.1?

package.json
```
{
  "name": "fet-admin-ui",
  "version": "1.0.0",
  "scripts": {
    "start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" ",
    "lite": "lite-server",
    "postinstall": "typings install",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "typings": "typings"
  },
  "license": "ISC",
  "dependencies": {
    "@angular/common": "~2.0.1",
    "@angular/compiler": "~2.0.1",
    "@angular/compiler-cli": "0.6.3",
    "@angular/core": "~2.0.1",
    "@angular/forms": "~2.0.1",
    "@angular/http": "~2.0.1",
    "@angular/platform-browser": "~2.0.1",
    "@angular/platform-browser-dynamic": "~2.0.1",
    "@angular/router": "~3.0.1",
    "@angular/upgrade": "~2.0.1",
    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.39",
    "zone.js": "^0.6.25",
    "angular2-in-memory-web-api": "0.0.21",

    "angular2-modal": "^2.0.0",
    "bootstrap": "^3.3.7",
    "font-awesome": "^4.6.3",
    "jquery": "^3.1.1",
    "momentjs": "^1.1.17",
    "ng2-translate": "^2.5.0"
  },
  "devDependencies": {
    "concurrently": "^3.0.0",
    "tslint": "^3.15.1",
    "lite-server": "^2.2.0",
    "typescript": "^2.0.3",
    "typings": "^1.4.0"
  }
}
```
typings.json:
```
{
  "globalDependencies": {
    "core-js": "registry:dt/core-js#0.0.0+20160725163759",
    "jasmine": "registry:dt/jasmine#2.2.0+20160621224255",
    "node": "registry:dt/node#6.0.0+20160909174046"
  }
}
```

tsconfig.json

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  }
}

```

it has a same issue:
```
node_modules/angular2-modal/esm/models/errors.d.ts(1,1): error TS2688: Cannot find type definition file for 'node'.
node_modules/angular2-modal/esm/providers/modal.d.ts(1,1): error TS2688: Cannot find type definition file for 'node'.
```

**Comment by Hassan121Cs** [comment]
trying to Migrate from Angular 2 to angular 4
Got these two errors now:
Build:Cannot Find type definition file for 'mocha'
Build:Cannot Find type definition file for 'node'

**Comment by nebiljabari** [comment]
@Hassan121Cs don't use Mocha but I solved : 

> Build:Cannot Find type definition file for 'node'

By re-importing the specific `@types/node` package used by my project.
In my case : `$ npm i -D @types/node@6.0.10`

Then modifing the variable at line 85
from : `declare var module: NodeModule;` to : `declare var module: {id: string};` _(causing an error)_

**Comment by parassachapara** [comment]
add types in your tsconfig file

{
  "compileOnSave": true,
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [ "es2016", "dom" ],
    "noImplicitAny": false,
    "suppressImplicitAnyIndexErrors": true, 
    "types": [      <<<=============================================
      "node"
    ]
  }
}

**Comment by sophiewjzhang** [comment]
This worked perfectly.  Thanks for the tip.  
The change I made: in my tsconfig.json:
{
...
  "compilerOptions": {
   ...
    "types": ["node"]
   ...
  },
...
}

**Comment by dcsan** [comment]
@parassachapara please triple quote code! with > ` ` ` marks
https://guides.github.com/features/mastering-markdown/#examples
