### ISSUE TITLE
error TS1110: Type expected.

### ISSUE THREAD

**Issue by yahyaKacem** [shlomiassaf/angular2-modal#55]
after updating to 0.1.3 I received this error during build:
>angular2-modal/dist/commonjs/models/ModalConfig.d.ts(1,42): error TS1110: Type expected.

even though modal still work find.

**Comment by shoudaos** [comment]
+

**Comment by shoudaos** [comment]
I have also this error with error above:
TS2362: The left-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.
TS2363: The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

**Comment by dbandstra** [comment]
That's because he's now using string literal types, which is a feature added in TypeScript 1.8. You could either upgrade your (global) TypeScript compiler or change BootstrapModalSize to be 'string' instead.

**Comment by shoudaos** [comment]
Oh, thanks very much. such a simple solution
